language: python
python:
- "3.6"

# setup environment
env:
- DJANGO_VERSION=2.0.2

# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- coverage run --source=. --omit '*__init__*,*wsgi*,*manage*,*test*,*prod_env.py*,*settings/*,*prehab_app/admin*,*prehab_app/apps*,*prehab_app/urls*,*prehab/fixtures*,*prehab/urls*,prehab/permissions.py' manage.py test prehab_app --noinput --settings=prehab.settings

# run coveralls after successful tests
after_success:
- coveralls


