language: python
python:
- "3.6"

# setup environment
env:
- DJANGO_VERSION=2.0.2

# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- coverage run manage.py test prehab_app --noinput

# run coveralls after successful tests
after_success:
- coveralls


