# Generated by Django 2.0.2 on 2018-03-29 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_patient', models.IntegerField(choices=[(1, 'Diabéticos'), (2, 'Insuficientes Renais'), (3, 'Desnutridos'), (4, 'vegetarianos'), (6, 'hipertensos'), (7, 'Normal')], default=7)),
            ],
        ),
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_user', models.IntegerField(choices=[(1, 'Full Access'), (2, 'Doctor Permissions'), (3, 'Patient Permissions'), (4, 'No Access')], default=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('department', models.CharField(max_length=50)),
                ('id_doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prehab_app.User', verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('tag', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1)),
                ('id_patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prehab_app.User', verbose_name='id')),
                ('type_of_patient', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to='prehab_app.PatientType')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='type_of_user',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to='prehab_app.TypeUser'),
        ),
    ]
