# Generated by Django 2.0.2 on 2018-04-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleweektask',
            name='times_per_week',
            field=models.IntegerField(default=1),
        ),
    ]
