# Generated by Django 2.0.2 on 2018-04-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weektaskschedule',
            name='repetition_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
