# Generated by Django 2.0.2 on 2018-03-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='type_of_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prehab_app.PatientType'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_of_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prehab_app.TypeUser'),
        ),
    ]
