# Generated by Django 2.0.2 on 2018-04-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTaskInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('was_difficult', models.BooleanField(default=False)),
                ('patient_notes', models.CharField(max_length=256)),
                ('seen_by_doctor', models.BooleanField(default=False)),
                ('doctor_notes', models.CharField(max_length=256, null=True)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='prehab_app.Doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='prehab_app.Patient')),
                ('patient_task', models.ForeignKey(db_column='patient_task_schedule_id', on_delete=django.db.models.deletion.CASCADE, to='prehab_app.PatientTaskSchedule')),
            ],
            options={
                'db_table': 'patient_task_info',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='patient_task_info',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient_task_info',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
