# Generated by Django 2.0.2 on 2018-04-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttaskschedule',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Ongoing'), (3, 'Completed'), (4, 'Not Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='prehab',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Ongoing'), (3, 'Completed'), (4, 'Not Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Ongoing'), (3, 'Completed'), (4, 'Not Completed')], default=1),
        ),
        migrations.DeleteModel(
            name='PatientTaskScheduleStatus',
        ),
        migrations.DeleteModel(
            name='PrehabStatus',
        ),
        migrations.DeleteModel(
            name='TaskScheduleStatus',
        ),
    ]
