# Generated by Django 2.0.2 on 2018-04-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttaskschedule',
            name='patient_notes',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
