# Generated by Django 2.0.2 on 2018-04-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0002_weektaskschedule_repetition_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttaskschedule',
            name='prehab',
            field=models.ForeignKey(db_column='prehab_id', on_delete=django.db.models.deletion.CASCADE, related_name='patient_task_schedule', to='prehab_app.Prehab'),
        ),
        migrations.AlterField(
            model_name='patienttaskschedule',
            name='task',
            field=models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='patient_task', to='prehab_app.Task'),
        ),
    ]
