# Generated by Django 2.0.2 on 2018-04-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0002_auto_20180423_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskschedule',
            name='status',
        ),
    ]
