# Generated by Django 2.0.2 on 2018-04-04 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0002_scheduleweektask_times_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='prehab',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=None, on_delete=django.db.models.deletion.CASCADE, to='prehab_app.Doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prehab',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='prehab_app.Patient'),
            preserve_default=False,
        ),
    ]
