# Generated by Django 2.0.2 on 2018-04-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0002_auto_20180421_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttaskschedule',
            name='doctor_notes',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='patienttaskschedule',
            name='patient_notes',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
