# Generated by Django 2.0.2 on 2018-03-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0002_auto_20180329_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id_doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prehab_app.User'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prehab_app.User'),
        ),
    ]
