# Generated by Django 2.0.2 on 2018-04-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0003_remove_taskschedule_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512, null=True)),
                ('multimedia_link', models.CharField(max_length=512, null=True)),
                ('meal_type', models.IntegerField(choices=[(1, 'Pequeno Almoço'), (2, 'Lanche'), (3, 'Refeição Completa')], default=2)),
            ],
            options={
                'db_table': 'meal',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MealConstraintType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('constraint_type', models.ForeignKey(db_column='constraint_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='constraint_type', to='prehab_app.ConstraintType')),
                ('meal', models.ForeignKey(db_column='meal_id', on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='prehab_app.Meal')),
            ],
            options={
                'db_table': 'meal_constraint_type',
                'ordering': ['-id'],
            },
        ),
    ]
