# Generated by Django 2.0.2 on 2018-04-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0003_auto_20180416_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttaskschedule',
            name='finished_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
