# Generated by Django 2.0.2 on 2018-04-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0003_auto_20180404_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='number_of_weeks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='title',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
