# Generated by Django 2.0.2 on 2018-04-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0004_auto_20180404_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskschedule',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to='prehab_app.User'),
        ),
    ]
