# Generated by Django 2.0.2 on 2018-04-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0004_patienttaskschedule_finished_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prehab',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to='prehab_app.User'),
        ),
    ]
