# Generated by Django 2.0.2 on 2018-04-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0004_auto_20180421_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttaskschedule',
            name='actuall_repetitions',
        ),
        migrations.AddField(
            model_name='patienttaskschedule',
            name='doctor_notes',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='patienttaskschedule',
            name='patient_notes',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='patienttaskschedule',
            name='seen_by_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patienttaskschedule',
            name='was_difficult',
            field=models.BooleanField(default=False),
        ),
    ]
