# Generated by Django 2.0.2 on 2018-03-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0005_auto_20180329_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.OneToOneField(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prehab_app.User'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.OneToOneField(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prehab_app.User'),
        ),
    ]
