# Generated by Django 2.0.2 on 2018-04-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0005_auto_20180421_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256)),
                ('seen', models.BooleanField(default=False)),
                ('doctor_notes', models.CharField(max_length=256, null=True)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='prehab_app.Doctor')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='doctorpatient',
            name='doctor',
            field=models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='prehab_app.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorpatient',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='prehab_app.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prehab_app.User'),
        ),
        migrations.AlterField(
            model_name='prehab',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to='prehab_app.Doctor'),
        ),
        migrations.AlterField(
            model_name='prehab',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='prehab_patient', to='prehab_app.Patient'),
        ),
        migrations.AddField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='prehab_app.Patient'),
        ),
    ]
