# Generated by Django 2.0.2 on 2018-05-01 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0005_meal_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMealSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('day_number', models.IntegerField()),
                ('meal_order', models.IntegerField(choices=[(1, 'Pequeno Almoço'), (2, 'Lanche da Manhã'), (3, 'Almoço'), (4, 'Lanche da Tarde'), (5, 'Jantar')], default=1)),
                ('meal', models.ForeignKey(db_column='meal_id', on_delete=django.db.models.deletion.CASCADE, related_name='patient_meal', to='prehab_app.Meal')),
                ('prehab', models.ForeignKey(db_column='prehab_id', on_delete=django.db.models.deletion.CASCADE, related_name='patient_meal_schedule', to='prehab_app.Prehab')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'patient_meal_schedule',
            },
        ),
    ]
