# Generated by Django 2.0.2 on 2018-04-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0005_auto_20180404_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleWeekTask',
            new_name='WeekTaskSchedule',
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='status',
            field=models.ForeignKey(db_column='status_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='prehab_app.TaskScheduleStatus'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='weektaskschedule',
            table='week_task_schedule',
        ),
    ]
