# Generated by Django 2.0.2 on 2018-04-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0006_auto_20180408_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskschedule',
            name='status',
            field=models.ForeignKey(db_column='status_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='prehab_app.TaskScheduleStatus'),
        ),
    ]
