# Generated by Django 2.0.2 on 2018-04-10 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0007_auto_20180408_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weektaskschedule',
            name='task',
            field=models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='task', to='prehab_app.Task'),
        ),
        migrations.AlterField(
            model_name='weektaskschedule',
            name='task_schedule',
            field=models.ForeignKey(db_column='task_schedule_id', on_delete=django.db.models.deletion.CASCADE, related_name='week_task_schedule', to='prehab_app.TaskSchedule'),
        ),
    ]
