# Generated by Django 2.0.2 on 2018-05-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0007_auto_20180501_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(choices=[(1, 'Respiratório'), (2, 'Endurance'), (3, 'Muscular')], db_column='task_type_id'),
        ),
    ]
