# Generated by Django 2.0.2 on 2018-04-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0008_auto_20180410_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
