# Generated by Django 2.0.2 on 2018-05-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prehab_app', '0009_auto_20180516_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconstrainttype',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='patient_constraints', to='prehab_app.Patient'),
        ),
        migrations.AlterField(
            model_name='prehab',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Ongoing'), (3, 'Completed'), (4, 'Canceled')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
